# Generated by Django 2.0 on 2018-04-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('download_url', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('size', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
