# Generated by Django 2.0 on 2018-04-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='media',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
